### ISSUE TITLE
1.0.4 Update has broken admin storage upload

### ISSUE THREAD

**Issue by xorinzor** [pagekit/pagekit#690] opened 2016-07-01 15:46 UTC
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!

## Problem

When you try to upload something to storage in the admin panel it will throw a javascript error, this has been confirmed on multiple PageKit installations that updated from the previous version (@luizjrdeveloper_twitter has confirmed this also happens on a clean install)

EDIT: it seems the javascript everywhere is broken now.

upload.min.js?v=fd15:2 Uncaught TypeError: Cannot read property 'push' of undefined
upload.min.js?v=fd15:2 Uncaught TypeError: Cannot read property 'replace' of undefined

## Technical Details

- Pagekit version: 1.0.4
- Webserver:Apache
- Database: MySQL 5
- PHP Version: 5.6.22

## Troubleshooting

- [x ] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x ] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x ] I have tried disabling all installed extensions
- [x ] I have checked the browser developer console for JavaScript errors

**Comment by luizjrdeveloper** [comment] 2016-07-01 15:56
He is helping me to send the problem is happening to me.

**Comment by malles** [comment] 2016-07-01 16:08
This is a UIkit issue. It should be fixed in the develop branch there.

**Comment by xorinzor** [comment] 2016-07-01 16:09
@malles pagekit pushed it with the update, breaking it, though.

Despite this maybe beeing an UIKit issue, this should've been tested before the update was pushed.

**Comment by MalteScharenberg** [comment] 2016-07-01 16:50
Fixed in 1.0.5

**Closed by MalteScharenberg** 2016-07-01 16:50 UTC

**Comment by FDiskas** [comment] 2016-10-30 17:15
:pencil: Not realy. 
```Uncaught TypeError: Cannot read property 'replace' of undefined```
then trying to upload an image. And image is not uploaded
![gnome-shell-imgur-3chhqy](https://cloud.githubusercontent.com/assets/468006/19838313/197b6982-9ed5-11e6-9a9e-686d8232985c.png)

**Comment by FDiskas** [comment] 2016-10-30 18:18
:truck: Maby it will help to investigate:
http://i.imgur.com/dCJx92m.png

**Comment by MalteScharenberg** [comment] 2016-11-02 10:45
@FDiskas Your issue seems not to be related to the issue discussed in this threat (same effect but different cause). Please open a new issue with a detailed description of your setup (inclusive the translation files you are using). Maybe this is related to this: https://github.com/pagekit/pagekit/issues/702?
