### ISSUE TITLE
index.php on NGINX

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#765] opened 2016-10-25 09:33 UTC
## Problem

Hello, I am using Pagekit 1.0.8 with NGINX. I followed the instructions to enable pretty urls on NGINX.

Now I can access a page using www.example.com/index.php/blog and www.example.com/blog . Both URLs are showing the blog page.

If I click "blog" in the menu this item is linked to www.example.com/index.php/blog .
## Technical Details
- Pagekit version: 1.0.8
- Webserver: NGINX
- Database: SQLite
- PHP Version: 5.6.24

**Comment by tobbexiv** [comment] 2016-10-26 20:16
Looks like a duplicate of #505 to me. There are also three possible solutions posted to solve it until an option to force it is implemented in Pagekit itself.

**Comment by MalteScharenberg** [comment] 2017-01-30 13:09
Duplicate of #505.

**Closed by MalteScharenberg** 2017-01-30 13:09 UTC
