### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 

### ISSUE THREAD

**Issue by Kristiansky** [pagekit/pagekit#890] opened 2018-01-30 09:45 UTC
I have moved my website from one server to another.
Everything went smooth, except for the Blog module. When i enter the Blog module and try to edit my articles, the Blog is not accessible, it throws the following exception:
```
DriverException in AbstractMySQLDriver.php line 115:
An exception occurred while executing 'SELECT user_id, name, username FROM pk_blog_post INNER JOIN pk_system_user ON user_id = pk_system_user.id GROUP BY user_id, name':

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pmgpagekit.pk_system_user.username' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by SPQRInc** [comment] 2018-01-30 09:46
Duplicate of https://github.com/pagekit/pagekit/issues/889

**Closed by SPQRInc** 2018-01-30 09:46 UTC
