### ISSUE TITLE
Error when i try to enable new theme from marketplace

### ISSUE THREAD

**Issue by Cr0iX** [pagekit/pagekit#849] opened 2017-07-13 14:12 UTC
## Problem
I get this error after pressing enable:

Not Found

The requested URL /tmp/admin/system/package/themes was not found on this server.

## Technical Details

- Pagekit version: 1.0.12
- Webserver: apache
- Database: mysql
- PHP Version: PHP 5.6.30

**Comment by Cr0iX** [comment] 2017-07-13 14:13
index.php is missing from the url

**Comment by SPQRInc** [comment] 2017-07-13 14:13
Does this happen with all themes you try to install?

**Comment by SPQRInc** [comment] 2017-07-13 14:15
You mean on `/tmp/admin/system/package/themes`? This should be a path, not an URL.

**Comment by Cr0iX** [comment] 2017-07-13 14:15
Yes, well i tried dolce, minimal and avanti.

**Comment by SPQRInc** [comment] 2017-07-13 14:22
I can not confirm this on my installation.

maybe a duplicate of https://github.com/pagekit/pagekit/issues/670 ?

@MalteScharenberg : Did you find a solution for this?

**Comment by Cr0iX** [comment] 2017-07-13 14:27
I have the rewrite module installed. As stated in #670, where one posted: "Solved rewrite_module issue"

**Comment by tobbexiv** [comment] 2017-07-16 21:22
You mean you have the apache mod_reqrite installed? Can you access any page of your homepage without the `index.php` in the url?

**Comment by Cr0iX** [comment] 2017-07-17 07:43
Yes i ahave mod_rewrite installed.
I can access www.website.com and it shows the index.php without it standing there.
But i cannot access index.php/om (a page created through pagekit)  without index.php being in front.

If it helps i can give access to the pagekit webpanel, to a dev or someone like that?

**Comment by SPQRInc** [comment] 2017-10-19 14:25
Could be helpful.

**Comment by SPQRInc** [comment] 2018-01-03 08:33
Closed, as there was no update/still missing information.

Feel free to reopen :)

**Closed by SPQRInc** 2018-01-03 08:33 UTC
Labels: Needs more info
