### ISSUE TITLE
Scrolling on mobile (Dashboard) moves the widgets around

### ISSUE THREAD

**Issue by iamswain** [pagekit/pagekit#552] opened 2016-03-02 12:00 UTC
Due to the touch event, the widgets get moved, making scrolling on the dashboard kind of tough.

**Comment by MalteScharenberg** [comment] 2016-03-02 15:40
We are thinking about adding a drag handle to the widgets to avoid this issue.
Thanks for reporting!

**Comment by iamswain** [comment] 2016-03-03 22:24
Sweet! That would definitely help!

**Comment by MalteScharenberg** [comment] 2017-06-29 12:47
Duplicate of #497.

**Closed by MalteScharenberg** 2017-06-29 12:47 UTC
